In [4]:
import os
os.chdir("../src")


In [10]:
import tensorflow as tf
import numpy as np
from dataloader import qm9_parse, qm9_fetch
import dmol
import torch
import torch.nn as nn


In [11]:
qm9_records = qm9_fetch()

data = qm9_parse(qm9_records)


Found existing record file, delete if you want to re-fetch


In [12]:
for d in data:
    print(d)
    break


((<tf.Tensor: shape=(5,), dtype=int64, numpy=array([6, 1, 1, 1, 1])>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-1.2698136e-02,  1.0858041e+00,  8.0009960e-03, -5.3568900e-01],
       [ 2.1504159e-03, -6.0313176e-03,  1.9761203e-03,  1.3392100e-01],
       [ 1.0117308e+00,  1.4637512e+00,  2.7657481e-04,  1.3392200e-01],
       [-5.4081506e-01,  1.4475266e+00, -8.7664372e-01,  1.3392299e-01],
       [-5.2381361e-01,  1.4379326e+00,  9.0639728e-01,  1.3392299e-01]],
      dtype=float32)>), <tf.Tensor: shape=(16,), dtype=float32, numpy=
array([ 1.0000000e+00,  1.5771181e+02,  1.5770998e+02,  1.5770699e+02,
        0.0000000e+00,  1.3210000e+01, -3.8769999e-01,  1.1710000e-01,
        5.0480002e-01,  3.5364101e+01,  4.4748999e-02, -4.0478931e+01,
       -4.0476063e+01, -4.0475117e+01, -4.0498596e+01,  6.4689999e+00],
      dtype=float32)>)


In [16]:
# def convert_record(d):
#     # break up record
#     (e, x), y = d
#     #
#     e = e.numpy()
#     x = x.numpy()
#     r = x[:, :3]
#     # make ohc size larger
#     # so use same node feature
#     # shape later
#     ohc = np.zeros((len(e), 16))
#     ohc[np.arange(len(e)), e - 1] = 1
#     return (ohc, r), y.numpy()[13] # This can be changed to any other variable. Number 6 is homo and number 13 is enthalpy.

def convert_record(d):
    # break up record
    (e, x), y = d
    #
    e = e.numpy()
    x = x.numpy()
    r = x[:, :3]
    # make ohc size larger
    # so use same node feature
    # shape later
    embedding = nn.Embedding(16, 128, padding_idx=0)

    e = torch.tensor(e)
    e = embedding(e)


    return (e, r), y.numpy()[13] # This can be changed to any other variable. Number 6 is homo and number 13 is enthalpy.


for d in data:
    (e, x), y = convert_record(d)
    print("Element one hots\n", e)
    print("Coordinates\n", x)
    print("Label:", y)
    break


Element one hots
 tensor([[ 7.1349e-01, -5.3546e-01, -1.4349e+00, -5.7822e-02, -7.1338e-01,
         -7.9947e-01, -6.3257e-01,  1.4867e+00,  2.5046e-01, -5.8075e-01,
         -4.3556e-01, -1.6540e+00,  1.0721e+00,  1.6596e-01,  4.0214e-01,
         -1.2918e+00, -1.2482e-01,  1.2914e+00,  7.9591e-01,  6.9152e-01,
          2.2871e+00, -7.0317e-02, -7.2225e-01, -1.1388e+00, -2.8872e-01,
         -7.3712e-01,  8.9914e-01, -1.2043e-01, -1.1166e-01, -4.2256e-01,
          5.6089e-01,  2.4724e-04,  6.4595e-01, -7.1833e-01,  7.5397e-01,
         -7.3912e-01,  6.9502e-01, -5.3815e-01,  1.2386e+00, -1.6510e+00,
         -4.8099e-01,  1.9623e+00,  2.1592e+00, -6.4000e-01, -5.9710e-01,
          3.2327e-01,  4.4501e-01,  5.2162e-01, -1.2738e-01, -3.0943e-02,
         -1.3371e+00, -4.0318e-01, -1.8980e-01,  8.2522e-02,  5.7104e-01,
          1.0842e+00,  1.7161e+00,  8.5507e-02, -2.4359e-01, -7.3303e-01,
          9.4842e-01,  8.6956e-01, -2.7203e-01, -2.4485e+00,  3.7147e-01,
          4.8419e-01

In [ ]:
# make embedding of
